# FROM node:24-alpine3.21 AS builder

# WORKDIR /app

# COPY package*.json ./

# # ARG NPM_REGISTRY=https://registry.npmjs.org
# # RUN --mount=type=cache,target=/root/.npm \
#     # npm ci --registry=${NPM_REGISTRY} --prefer-offline --no-audit --no-fund
# RUN npm ci
# COPY prisma ./prisma
# RUN npx prisma generate

# COPY . .
# RUN npm run build && npm prune --omit=dev


# FROM node:24-alpine3.21 AS runner

# WORKDIR /app

# ENV NODE_ENV=production

# # Create non-root user for security
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# # Install production dependencies only
# # COPY package*.json ./
# # RUN --mount=type=cache,target=/root/.npm \
# #     npm ci --omit=dev --no-audit --no-fund --prefer-offline

# # Copy Prisma artifacts from builder
# COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
# COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma
# COPY --from=builder /app/prisma ./prisma

# # Copy compiled output
# COPY --from=builder /app/dist ./dist

# # Switch to non-root user
# USER appuser

# # Entrypoint is volume-mounted at runtime via docker-compose
# # Fallback: if no entrypoint mounted, just run the CMD directly
# CMD ["node", "dist/index.js"]

FROM node:24-alpine3.24

WORKDIR /app

COPY package*.json ./

RUN npm install

CMD ["sh"]