FROM node:24-alpine3.21

WORKDIR /usr/src/app

COPY ./frontend/package.json .
COPY ./frontend/package-lock.json .

RUN npm install --legacy-peer-deps

COPY . .  
# Copy all files including hidden ones

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]