FROM node:24-alpine3.21

WORKDIR /app

COPY ./primBackend/package.json .
COPY ./primBackend/package-lock.json .

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

EXPOSE 3001

CMD ["npm", "run", "start"]