# FROM node:24-alpine3.21 AS builder

# WORKDIR /app

# ARG NEXT_PUBLIC_API_URL
# ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

# COPY package*.json ./
# # RUN --mount=type=cache,target=/root/.npm \
# #     npm ci --registry http://npm-cache:4873 --prefer-offline
# RUN npm ci
# COPY . .
# RUN npm run build

# FROM node:24-alpine3.21 AS runner

# WORKDIR /app

# ENV NODE_ENV=production
# ENV HOSTNAME=0.0.0.0

# # Create non-root user for security
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# COPY --from=builder /app/.next/standalone ./
# COPY --from=builder /app/.next/static ./.next/static
# COPY --from=builder /app/public ./public

# # Switch to non-root user
# USER appuser

# EXPOSE 3000
# CMD ["node", "server.js"]

FROM node:24-alpine3.21

WORKDIR /app

COPY package*.json ./

RUN npm install

CMD ["sh"]